### ISSUE TITLE
Include global_z_historical in np export

### ISSUE THREAD

**Issue by m-macaskill** [nzbri/chchpd#2]
In response to https://github.com/nzbri/redcap/issues/53, need to return two global_z values. The default `global_z` will now be the mean of all five domain means. So also need to return the new, additional `global_z_historical` variable, which excludes the language domain in case people wish to be compatible with earlier analyses.

Also need to export the newly-added neuropsyc exclusion variable.

**Comment by zenourn** [comment]
This will automatically happen when the repository on kratos is updated from GitHub - I'm going to do it over the weekend as want to commit another fix at the same time. I didn't actually intend for nzbri/redcap#53 to close, was all far to intelligent when I used the word 'Resolve' in the commit title!

**Comment by m-macaskill** [comment]
All good, I'll keep an eye on when it gets released and make changes in `chchpd` accordingly.

**Comment by zenourn** [comment]
Has now been released so `chchpd` can be updated.

**Comment by m-macaskill** [comment]
Resolved by https://github.com/nzbri/chchpd/commit/89683aabe0be2436f329ed51d9fc1cfee80207f5
