### ISSUE TITLE
Participants with more than one EEG1 session suffix have duplicated entries.

### ISSUE THREAD

**Issue by rezashr** [nzbri/chchpd#4]
For 208PDS, there are two sessions with EEG1 suffix, which import_sessions() would make it 4 entries and the age isn't correct in two of them. I think this is an issue in the map_to_universal_session_id().

**Comment by zenourn** [comment]
There is an implicit assumption that suffixes are unique within a subject. I really should enforce this in Alice, although it is flagged in the ErrorLog.txt:

2019-11-04 09:30:16,106 WARNING: (208PDS,EEG1) is not not mapped to a unique subject ID and date

Also a lot of CE1s that violate this

**Comment by rezashr** [comment]
Currently I'm getting around it by comparing the session_id and session_date. I think we should introduce a new check in the chchpd package to prevent similar issue. Otherwise, duplicate entries might get their ways into the analysis part.

**Comment by m-macaskill** [comment]
I think resolving it in `chchpd` is too far up the chain. This is an issue of data integrity that should be enforced earlier on. Once it comes to the  data output stage, all `chchpd` can do is to flag the conflict issue, as it can't know how to resolve it.

**Comment by zenourn** [comment]
I've fixed all the duplicated suffixes in Alice and ErrorLog.txt is now empty. Going forward, in the export script if ErrorLog.txt is non-zero in size then the contents should be emailed to me and I'll resolve the issues.
