### ISSUE TITLE
Authenticate issue

### ISSUE THREAD

**Issue by rezashr** [nzbri/chchpd#6]
Recently, I've noticed an error during the authentication process: "Sign in with Google temporarily disabled for this app, This app has not been verified yet by Google in order to use Google Sign In." 

Currently, the way around it is to create a project in the google cloud, enable drive and spreadsheet APIs, and then create a OAuth2.0 for it. The client_id and secret can be used in googlesheet::gs_auth() to proceed with the authentication.

**Comment by m-macaskill** [comment]
Note that we rely on a Google API that is about to be retired and authentication is apparently one of the things changing. Maybe this is the first symptom of that, although the V3 API isn't supposed to die until March 2020. Although it is still under active development, perhaps wee should be testing out `googlesheets4`, the successor to the `google sheets` package, so we stay ahead of any issues: https://github.com/tidyverse/googlesheets4/issues/58

**Comment by rezashr** [comment]
googlesheets4 uses gargle to authenticate (API V4), which fixes this issue. But it currently has some bugs and read_sheets is much slower than gs_read (caching can somehow reduce the impact). Might worth creating a development branch with googlesheets4.

**Comment by zenourn** [comment]
So just had to rerun the sensitive tests pipeline from scratch following my complete reinstall of R and encountered this issue! Any easy process I can follow to get this working again? This paper really is cursed ;-)

**Comment by rezashr** [comment]
To make things easier, I just created OAuth2 credentials for you. Please go to [https://console.cloud.google.com/apis/credentials?project=tidyverse](https://console.cloud.google.com/apis/credentials?project=tidyverse) and download your client ID and secret ID. 

You can then authenticate with googlesheets::gs_auth(key = "client_id", secret = "secret_id"). 

I think you should add this at the beginning of your code, otherwise it will ask to authenticate each time.

**Comment by zenourn** [comment]
Thanks Reza, that worked.

**Comment by m-macaskill** [comment]
I'll start a new dev branch to switch to the new `googlesheets4` package, but that is going to take some testing, and as Reza notes, that is being actively developed and so there might be some performance/bug issues. So not really a short-term solution.

**Comment by m-macaskill** [comment]
Should now be addressed in the 0.3.0 release, although we might continue to make this a smoother process.
