### ISSUE TITLE
Getting ready for the new version of Googlesheets4

### ISSUE THREAD

**Issue by rezashr** [nzbri/chchpd#9]
As of version 0.2.0 of googlesheets4, most of the functions are renamed and the old ones are deprecated. The initial convention was sheets_* for function names, but it is changing to gs4_* for most functions. For instance, sheets_auth() will be changed to gs4_auth() and so on. One exception would be range_read() to replace sheets_read().

Perhaps it would be ideal to start a new branch ready for the new version of gs4.

**Comment by m-macaskill** [comment]
Thanks, I hadn't seen this. Will amend accordingly and impose a minimum version number for the `googlesheets4` package so when people upgrade `chchpd`, they'll also get a version of `googlesheets4` compatible with the new naming scheme.

**Comment by rezashr** [comment]
CRAN is still using version 0.1.1, but it was released on March 2020. Won't be long until they update it to version 0.2.0 (development version on github).

**Comment by m-macaskill** [comment]
Ahh thanks, I was thinking of specifying the current development version, but of course that won't work via the CRAN update mechanism.

**Comment by m-macaskill** [comment]
Fixed by #10
